//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVienWithEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemsv
    {
        public int id { get; set; }
        public string masv { get; set; }
        public string mamon { get; set; }
        public string diemthi { get; set; }
        public string diemquatrinh { get; set; }
        public string diemtrungbinh { get; set; }
        public string trangthai { get; set; }
    
        public virtual monday monday { get; set; }
        public virtual sinhvien sinhvien { get; set; }
    }
}
