//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVienWithEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGiangVienEntities : DbContext
    {
        public QLGiangVienEntities()
            : base("name=QLGiangVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diemsv> diemsvs { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<GV> GVs { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<lop> lops { get; set; }
        public virtual DbSet<monday> mondays { get; set; }
        public virtual DbSet<sinhvien> sinhviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
