//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVienWithEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinhvien()
        {
            this.diemsvs = new HashSet<diemsv>();
        }
    
        public string masv { get; set; }
        public string hoten { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string sdt { get; set; }
        public string malop { get; set; }
        public string address { get; set; }
        public byte[] anhthe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diemsv> diemsvs { get; set; }
        public virtual lop lop { get; set; }
    }
}
